use std::{ffi::OsString, fs, io, path::PathBuf};
use uuid::Uuid;

const COLLECTION_FILENAME: &str = "COLLECTION";
const DEFAULT_COLLECTION_FILE: &str = "# @generated by llibre. DO NOT edit manually\n";

#[derive(Default)]
pub struct Entry {
    pub filename: String,
    pub name: String,
    pub authors: Vec<String>,
    pub year: u16,
    pub category: String,
}

pub struct Library {
    pub path: PathBuf,
    pub entries: Vec<Entry>,
}

impl Library {
    pub fn new(path: PathBuf) -> Self {
        Self {
            path,
            entries: Default::default(),
        }
    }

    pub fn create_entry(
        &mut self,
        path: PathBuf,
        category: String,
        name: String,
        authors: Vec<String>,
        year: u16,
    ) -> io::Result<()> {
        let category_dir = self.path.join(&category);

        if !fs::exists(&category_dir)? {
            fs::create_dir(&category_dir)?;
            fs::write(
                category_dir.join(COLLECTION_FILENAME),
                DEFAULT_COLLECTION_FILE,
            )?;
        }

        let bytes = fs::read(&path)?;
        let filename = PathBuf::from(Uuid::new_v4().to_string())
            .with_extension(path.extension().unwrap_or_default());

        fs::write(category_dir.join(&filename), bytes)?;

        let filename_string = match filename.to_str() {
            Some(x) => x.to_string(),
            None => {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidFilename,
                    "Failed to convert filename to String",
                ));
            }
        };

        let entry = Entry {
            filename: filename_string,
            name,
            authors,
            year,
            category,
        };

        Ok(self.push(entry))
    }

    #[inline]
    fn push(&mut self, entry: Entry) {
        self.entries.push(entry);
    }

    pub fn fetch_library(&mut self) -> io::Result<()> {
        let contents = fs::read_dir(&self.path)?;
        for maybe_entry in contents {
            let entry = maybe_entry?;
            let name_os = entry.file_name();
            if name_os == "conf.toml" {
                continue;
            }

            Self::expect_dir(&entry)?;

            let category = name_os
                .into_string()
                .map_err(Self::osstring_conversion_error)?;

            self.fetch_category(category, entry)?;
        }

        Ok(())
    }

    fn fetch_category(&mut self, category: String, dir_entry: fs::DirEntry) -> io::Result<()> {
        let contents = fs::read_to_string(dir_entry.path().join(COLLECTION_FILENAME))?;
        let books = contents.split("\n").skip(1);
        for book in books {
            if book == "" {
                continue;
            }; // deleted or missing line. it's ok

            let entry = match Self::parse_entry(&category, book) {
                Some(e) => e,
                None => return Err(Self::expect_data_in_collections()),
            };

            self.push(entry);
        }

        Ok(())
    }

    fn parse_entry(category: &str, data: &str) -> Option<Entry> {
        let mut parts = data.split(";;");
        let filename = parts.next()?.into();
        let year = match parts.next()?.parse::<u16>() {
            Ok(y) => Some(y),
            Err(_) => None,
        }?;

        let authors = parts
            .next()?
            .split(",")
            .map(|author| author.trim().into())
            .collect();

        let name = parts.next()?.into();

        Some(Entry {
            filename,
            name,
            authors,
            year,
            category: category.into(),
        })
    }

    fn expect_dir(dir_entry: &fs::DirEntry) -> io::Result<()> {
        if dir_entry.file_type()?.is_dir() {
            return Ok(());
        }

        Err(io::Error::new(
            io::ErrorKind::NotADirectory,
            "Expected category directory, found file",
        ))
    }

    fn expect_data_in_collections() -> io::Error {
        io::Error::new(
            io::ErrorKind::InvalidData,
            "Invalid collection file. Please delete it and re-load all books again.",
        )
    }

    fn osstring_conversion_error(_: OsString) -> io::Error {
        io::Error::new(
            io::ErrorKind::InvalidFilename,
            "Failed to convert file name to String",
        )
    }
}
